language: "python"
sudo: false
python:
        - "2.6"
        - "2.7"
        - "3.3"
        - "3.4"
        - "3.5"
        - "pypy"
before_script:
        - "pip install ."
        - "mkdir -p /tmp/trequest-tests"
        - "cp trequests_tests.py /tmp/trequest-tests"
script: "nosetests /tmp/trequest-tests/"
